name: e_commerce_flutter
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  enum_to_string: ^2.0.1
  get: ^4.6.5
  bottom_navy_bar: ^6.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_rating_bar: ^4.0.0
  font_awesome_flutter: ^10.1.0
  animations: ^2.0.3

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/